[package]
name = "cli-pocket-daemon"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "cli-pocket daemon binary."

[[bin]]
name = "cli-pocket-daemon"
path = "src/main.rs"

[dependencies]
cli-pocket-daemon-core = { path = "../daemon-core" }
cli-pocket-crypto      = { path = "../../shared/crypto" }
cli-pocket-proto       = { path = "../../shared/proto" }

anyhow             = "1"
clap               = { workspace = true }
hex                = "0.4"
tokio              = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
toml               = "=0.8.23"
tracing            = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid               = { workspace = true }

[lints]
workspace = true
