[package]
name = "cli-pocket-tauri-bindings"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Native bindings for cli-pocket-client-core in Tauri apps."

[lints]
workspace = true

[dependencies]
cli-pocket-client-core = { path = "../client-core" }

async-trait = { workspace = true }
futures-util = { workspace = true, features = ["sink"] }
getrandom = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
