name: release windows-x86_64

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (without leading v)"
        required: true

jobs:
  build:
    uses: ./.github/workflows/release-platform.yml
    with:
      version: ${{ inputs.version }}
      name: windows-x86_64
      os: windows-2022
      target: x86_64-pc-windows-msvc
      build_daemon: true
      build_relay: true
      build_desktop: true
      build_web: false
      build_android: false
      build_ios: false
      node_required: true
      tauri_required: true
      wasm_pack_install: none
      tauri_bundles: msi
    secrets: inherit
